logging:
  level:
    com.volvo.emspassignment.mapper: debug
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

custom:
  id-config:
    country-codes: CN,US,UK,JP,KR,DE,RU,CA
    vendor-codes: AB,CD,EF,GH,IJ,KL,MN