spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsp?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: emsp_user
    password: emsp_password
    driver-class-name: com.mysql.cj.jdbc.Driver