### Create account Post request to lcoalhost server
POST http://localhost:8081/account
Content-Type: application/json

{
  "email": "splash@nba.com",
  "name": "Steve Curry",
  "username": "SC40000",
  "password": "Scurry88888",
  "accountStatus": "CREATED"
}

### Change account status PATCH request to lcoalhost server
PATCH http://localhost:8081/account/cpaul@nba.com/status
Content-Type: application/json

{
    "accountStatus": "ACTIVATED"
}

### Query account by lastUpdated field DESC with pagination GET request to lcoalhost server
GET http://localhost:8081/account/search
Content-Type: application/json

{
  "pageNum": 1,
  "pageSize": 2
}

### Change account status PATCH request to lcoalhost server
PATCH http://localhost:8081/account/changeAccountStatus/9
Content-Type: application/json

{
  "id": 9,
  "email": "123456@163.com",
  "name": "Hommie",
  "username": "hjasfj",
  "password": "Wasd123456",
  "accountStatus": "ACTIVATED"
}

### Create card POST request to lcoalhost server
POST http://localhost:8082/card
Content-Type: application/json

{
  "cardNum": "1111222233334444",
  "cardStatus": "WEQ"
}

### Update card PATCH request to lcoalhost server
PATCH http://localhost:8082/card/allocation
Content-Type: application/json

{
  "id": 12,
  "accountId": 16
}

### Change card status PATCH request to lcoalhost server
PATCH http://localhost:8082/card/status
Content-Type: application/json

{
  "id": 6,
  "cardStatus": "DEACTIVATED"
}

### Query card by lastUpdated field DESC with pagination GET request to lcoalhost server
GET http://localhost:8082/card/search
Content-Type: application/json

{
  "pageNum": 1,
  "pageSize": 2
}