### Create account Post request to lcoalhost server
POST http://localhost:8081/account
Content-Type: application/json

{
  "email": "cpaul@nba.com",
  "name": "Chris Paul",
  "username": "Cpaul",
  "password": "Cp3333333",
  "accountStatus": "CREATED"
}

### Change account status PATCH request to lcoalhost server
PATCH http://localhost:8081/account/cpaul@nba.com/status
Content-Type: application/json

{
    "accountStatus": "ACTIVATED"
}

### Query account by lastUpdated field DESC with pagination GET request to lcoalhost server
GET http://localhost:8081/account/search
Content-Type: application/json

{
  "pageNum": 1,
  "pageSize": 2
}

### Change account status PATCH request to lcoalhost server
PATCH http://localhost:8081/account/changeAccountStatus/9
Content-Type: application/json

{
  "id": 9,
  "email": "123456@163.com",
  "name": "Hommie",
  "username": "hjasfj",
  "password": "Wasd123456",
  "accountStatus": "ACTIVATED"
}

### Create card POST request to lcoalhost server
POST http://localhost:8082/card/create
Content-Type: application/json

{
  "cardNum": "1234567890111213",
  "cardStatus": "CREATED"
}

### Update card PATCH request to lcoalhost server
PATCH http://localhost:8082/card/assign/12
Content-Type: application/json

{
  "id": 5,
  "cardNum": "1234567890111213",
  "accountId": 1,
  "cardStatus": "ASSIGNED"
}

### Change card status PATCH request to lcoalhost server
PATCH http://localhost:8082/card/changeCardStatus/6
Content-Type: application/json

{
  "id": 6 ,
  "cardNum": "1234567890111213",
  "cardStatus": "ACTIVATED"
}

### Query card by lastUpdated field DESC with pagination GET request to lcoalhost server
GET http://localhost:8082/card/queryCardPage
Content-Type: application/json

{
  "pageNum": 1,
  "pageSize": 2
}